export const SELECT_MENU = 'SELECT_MENU';
export type SELECT_MENU = typeof SELECT_MENU;

export const ADD_STRUCTURE_ITEM = 'ADD_STRUCTURE_ITEM';
export type ADD_STRUCTURE_ITEM = typeof ADD_STRUCTURE_ITEM;

export const REMOVE_STRUCTURE_ITEM = 'REMOVE_STRUCTURE_ITEM';
export type REMOVE_STRUCTURE_ITEM = typeof REMOVE_STRUCTURE_ITEM;

export const MOVE_STRUCTURE_ITEM = 'MOVE_STRUCTURE_ITEM';
export type MOVE_STRUCTURE_ITEM = typeof MOVE_STRUCTURE_ITEM;
